/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Product_View.java
 *
 * Created on Jun 14, 2011, 10:09:17 PM
 */
package views;

import java.awt.event.ActionListener;

import models.Product_Model;


/**
 *
 * @author warz07
 */
public class Product_View extends javax.swing.JFrame {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Product_Model model;
	/** Creates new form Product_View */
    public Product_View(Product_Model model) {
    	this.model = model;
        initComponents();
    }
    
    public void close(){
    	this.dispose();
    }
    public void addSaveListener(ActionListener save){
    	
    }
    
    public void addCloseListener(ActionListener close){
    	
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SearchTab = new javax.swing.JTabbedPane();
        productSearchTable = new javax.swing.JPanel();
        SearchButton = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        advanceSearch = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        productIDLabel = new javax.swing.JLabel();
        productSearch = new javax.swing.JTextField();
        referenceLabel = new javax.swing.JLabel();
        referenceProduct = new javax.swing.JTextField();
        productNameSearchLabel = new javax.swing.JLabel();
        productNameSearch = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        priceinCashSearch = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        finalPriceSearch = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        priceInTermSearch = new javax.swing.JTextField();
        Search = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        descriptionSearch = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        sortPriceProduct = new javax.swing.JCheckBox();
        sortProductName = new javax.swing.JCheckBox();
        sortProductDate = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();
        unitySearch = new javax.swing.JComboBox();
        jLabel27 = new javax.swing.JLabel();
        currentStockSearch = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        productCostSearch = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        trademarkProduct = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        ProductHeader = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        productName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        ProductId = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        productQuantity = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        Clear = new javax.swing.JButton();
        Save = new javax.swing.JButton();
        Close = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        productDescription = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        purchasePrice = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        averagePrice = new javax.swing.JTextField();
        buyingPrice = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        Strprice = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        ipiPrice = new javax.swing.JTextField();
        salesLabel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        refreferenceOneProduct = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        referenceTwoProduct = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        locationProduct = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        groupProduct = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        subgroupProduct = new javax.swing.JTextField();
        weightedLabel = new javax.swing.JLabel();
        yesWeighted = new javax.swing.JRadioButton();
        noWeighted = new javax.swing.JRadioButton();
        jLabel37 = new javax.swing.JLabel();
        weightProduct = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        stockProduct = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        initialEstimationProduct = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        minimalEstimation = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        profitMargin = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        validityProduct = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        nameInthePrinter = new javax.swing.JTextField();
        jLabel44 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        percentageRadioButton = new javax.swing.JRadioButton();
        noneRadioButton = new javax.swing.JRadioButton();
        jLabel45 = new javax.swing.JLabel();
        unityQuantity = new javax.swing.JTextField();
        jLabel46 = new javax.swing.JLabel();
        sizeProduct = new javax.swing.JTextField();
        jLabel47 = new javax.swing.JLabel();
        taxesProduct = new javax.swing.JTextField();
        jLabel48 = new javax.swing.JLabel();
        commercialName = new javax.swing.JTextField();
        jLabel49 = new javax.swing.JLabel();
        averageCost = new javax.swing.JTextField();
        jLabel50 = new javax.swing.JLabel();
        averageFinalPrice = new javax.swing.JTextField();
        jLabel51 = new javax.swing.JLabel();
        promotionalPrice = new javax.swing.JTextField();
        jLabel52 = new javax.swing.JLabel();
        dateProductPriceChange = new javax.swing.JTextField();
        jLabel53 = new javax.swing.JLabel();
        inCashProduct = new javax.swing.JTextField();
        jLabel54 = new javax.swing.JLabel();
        inCashActual = new javax.swing.JTextField();
        jLabel55 = new javax.swing.JLabel();
        inTermProduct = new javax.swing.JTextField();
        jLabel56 = new javax.swing.JLabel();
        inTermActual = new javax.swing.JTextField();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        promotionPrice = new javax.swing.JTextField();
        jLabel59 = new javax.swing.JLabel();
        commissionPromotion = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        updateProductButton = new javax.swing.JButton();
        deleteProductButton = new javax.swing.JButton();
        cancelProductButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        updateTableProduct = new javax.swing.JTable();
        searchUpdateButtonProduct = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        productCodeUpdate = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        SearchTab.setName("SearchTab"); // NOI18N

        productSearchTable.setName("productSearchTable"); // NOI18N

        SearchButton.setText("Search");
        SearchButton.setName("SearchButton"); // NOI18N

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 1, 18));
        jLabel8.setText("Search Product Information");
        jLabel8.setName("jLabel8"); // NOI18N

        advanceSearch.setText("Advanced Search");
        advanceSearch.setName("advanceSearch"); // NOI18N

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setName("jTable1"); // NOI18N
        jScrollPane2.setViewportView(jTable1);

        productIDLabel.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        productIDLabel.setText("*Product Code");
        productIDLabel.setName("productIDLabel"); // NOI18N

        productSearch.setName("productSearch"); // NOI18N

        referenceLabel.setFont(new java.awt.Font("Lucida Grande", 0, 12));
        referenceLabel.setText("Reference 1");
        referenceLabel.setName("referenceLabel"); // NOI18N

        referenceProduct.setName("referenceProduct"); // NOI18N

        productNameSearchLabel.setFont(new java.awt.Font("Lucida Grande", 0, 12));
        productNameSearchLabel.setText("*Product Name");
        productNameSearchLabel.setName("productNameSearchLabel"); // NOI18N

        productNameSearch.setName("productNameSearch"); // NOI18N

        jLabel10.setFont(new java.awt.Font("Lucida Grande", 0, 12));
        jLabel10.setText("Price In Cash");
        jLabel10.setName("jLabel10"); // NOI18N

        priceinCashSearch.setName("priceinCashSearch"); // NOI18N

        jLabel11.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        jLabel11.setText("Price In Term");
        jLabel11.setName("jLabel11"); // NOI18N

        jLabel12.setFont(new java.awt.Font("Lucida Grande", 0, 12));
        jLabel12.setText("Final Price");
        jLabel12.setName("jLabel12"); // NOI18N

        finalPriceSearch.setName("finalPriceSearch"); // NOI18N

        jLabel14.setIcon(new javax.swing.ImageIcon("/Users/warz07/Downloads/line2.png")); // NOI18N
        jLabel14.setName("jLabel14"); // NOI18N

        priceInTermSearch.setName("priceInTermSearch"); // NOI18N

        Search.setActionCommand("Search");
        Search.setLabel("Search");
        Search.setName("Search"); // NOI18N

        jLabel22.setText("Description");
        jLabel22.setName("jLabel22"); // NOI18N

        descriptionSearch.setName("descriptionSearch"); // NOI18N

        jLabel26.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(204, 0, 0));
        jLabel26.setText("SORT BY");
        jLabel26.setName("jLabel26"); // NOI18N

        sortPriceProduct.setText("PRICE");
        sortPriceProduct.setName("sortPriceProduct"); // NOI18N

        sortProductName.setText("NAME");
        sortProductName.setName("sortProductName"); // NOI18N

        sortProductDate.setText("DATE");
        sortProductDate.setName("sortProductDate"); // NOI18N

        jLabel9.setText("Product Unity");
        jLabel9.setName("jLabel9"); // NOI18N

        unitySearch.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "UN1", "UN2", "UN3", "UN4" }));
        unitySearch.setName("unitySearch"); // NOI18N

        jLabel27.setText("Current Stock");
        jLabel27.setName("jLabel27"); // NOI18N

        currentStockSearch.setName("currentStockSearch"); // NOI18N

        jLabel28.setText("Product Cost");
        jLabel28.setName("jLabel28"); // NOI18N

        productCostSearch.setName("productCostSearch"); // NOI18N

        jLabel29.setText("Note * items are required");
        jLabel29.setName("jLabel29"); // NOI18N

        jLabel36.setText("Trademark");
        jLabel36.setName("jLabel36"); // NOI18N

        trademarkProduct.setName("trademarkProduct"); // NOI18N

        org.jdesktop.layout.GroupLayout productSearchTableLayout = new org.jdesktop.layout.GroupLayout(productSearchTable);
        productSearchTable.setLayout(productSearchTableLayout);
        productSearchTableLayout.setHorizontalGroup(
            productSearchTableLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jLabel14, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(productSearchTableLayout.createSequentialGroup()
                .add(9, 9, 9)
                .add(jLabel8)
                .add(394, 394, 394)
                .add(jLabel29)
                .addContainerGap(400, Short.MAX_VALUE))
            .add(productSearchTableLayout.createSequentialGroup()
                .add(productSearchTableLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(productSearchTableLayout.createSequentialGroup()
                        .add(12, 12, 12)
                        .add(productSearchTableLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(productSearchTableLayout.createSequentialGroup()
                                .add(productSearchTableLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(productSearchTableLayout.createSequentialGroup()
                                        .add(productSearchTableLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                                            .add(org.jdesktop.layout.GroupLayout.LEADING, referenceProduct)
                                            .add(org.jdesktop.layout.GroupLayout.LEADING, referenceLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .add(org.jdesktop.layout.GroupLayout.LEADING, priceInTermSearch, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 80, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                        .add(productSearchTableLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                            .add(productSearchTableLayout.createSequentialGroup()
                                                .add(1, 1, 1)
                                                .add(priceinCashSearch, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 74, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                                .add(finalPriceSearch, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 74, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                            .add(productSearchTableLayout.createSequentialGroup()
                                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                                .add(productSearchTableLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                                    .add(jLabel9)
                                                    .add(unitySearch, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                                .add(18, 18, 18)
                                                .add(productSearchTableLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                                    .add(currentStockSearch)
                                                    .add(jLabel27))
                                                .add(18, 18, 18)
                                                .add(productSearchTableLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                                                    .add(org.jdesktop.layout.GroupLayout.LEADING, productCostSearch)
                                                    .add(org.jdesktop.layout.GroupLayout.LEADING, jLabel28))
                                                .add(18, 18, 18)
                                                .add(productSearchTableLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                                    .add(trademarkProduct, 0, 0, Short.MAX_VALUE)
                                                    .add(jLabel36)))))
                                    .add(productSearchTableLayout.createSequentialGroup()
                                        .add(productSearchTableLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                            .add(productIDLabel)
                                            .add(productSearch, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 117, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                        .add(18, 18, 18)
                                        .add(productSearchTableLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                            .add(productSearchTableLayout.createSequentialGroup()
                                                .add(productNameSearchLabel)
                                                .add(51, 51, 51)
                                                .add(jLabel22))
                                            .add(productSearchTableLayout.createSequentialGroup()
                                                .add(productNameSearch, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 130, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                                .add(descriptionSearch, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 265, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 152, Short.MAX_VALUE)
                                .add(productSearchTableLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(sortProductName)
                                    .add(productSearchTableLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                        .add(jLabel26)
                                        .add(sortPriceProduct))
                                    .add(sortProductDate)
                                    .add(Search))
                                .add(40, 40, 40))
                            .add(productSearchTableLayout.createSequentialGroup()
                                .add(jLabel10)
                                .add(18, 18, 18)
                                .add(jLabel11)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jLabel12)))
                        .add(110, 110, 110))
                    .add(productSearchTableLayout.createSequentialGroup()
                        .add(jScrollPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 858, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)))
                .add(SearchButton)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(advanceSearch)
                .add(34, 34, 34))
        );
        productSearchTableLayout.setVerticalGroup(
            productSearchTableLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(productSearchTableLayout.createSequentialGroup()
                .addContainerGap()
                .add(productSearchTableLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel8)
                    .add(jLabel29))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel14)
                .add(18, 18, 18)
                .add(productSearchTableLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(productSearchTableLayout.createSequentialGroup()
                        .add(productSearchTableLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(productSearchTableLayout.createSequentialGroup()
                                .add(productSearchTableLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                    .add(productSearchTableLayout.createSequentialGroup()
                                        .add(productIDLabel)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(productSearch, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                    .add(productSearchTableLayout.createSequentialGroup()
                                        .add(productSearchTableLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                            .add(productNameSearchLabel)
                                            .add(jLabel22))
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(productSearchTableLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                            .add(productNameSearch, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                            .add(descriptionSearch, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(productSearchTableLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                    .add(referenceLabel)
                                    .add(jLabel9)
                                    .add(jLabel27)))
                            .add(productSearchTableLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                .add(jLabel28)
                                .add(jLabel36)))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(productSearchTableLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(referenceProduct, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(unitySearch, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(currentStockSearch, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(productCostSearch, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(trademarkProduct, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(productSearchTableLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel10)
                            .add(jLabel11)
                            .add(jLabel12))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(productSearchTableLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(priceInTermSearch, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(priceinCashSearch, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(finalPriceSearch, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED))
                    .add(productSearchTableLayout.createSequentialGroup()
                        .add(jLabel26)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(sortPriceProduct)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(sortProductName)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(sortProductDate)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 13, Short.MAX_VALUE)
                .add(Search)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(productSearchTableLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(productSearchTableLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(SearchButton)
                        .add(advanceSearch))
                    .add(jScrollPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 439, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        SearchTab.addTab("Search Products", productSearchTable);

        jPanel1.setName("jPanel1"); // NOI18N

        ProductHeader.setFont(new java.awt.Font("Lucida Grande", 1, 18));
        ProductHeader.setText("Insert New Product");
        ProductHeader.setName("ProductHeader"); // NOI18N

        jLabel1.setIcon(new javax.swing.ImageIcon("/Users/warz07/Downloads/line2.png")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        productName.setName("productName"); // NOI18N

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        jLabel2.setText("*Product Name");
        jLabel2.setName("jLabel2"); // NOI18N

        ProductId.setName("ProductId"); // NOI18N
        ProductId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProductIdActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 12));
        jLabel3.setText("*Product Code");
        jLabel3.setName("jLabel3"); // NOI18N

        productQuantity.setName("productQuantity"); // NOI18N

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        jLabel4.setText("*Product Quantity");
        jLabel4.setName("jLabel4"); // NOI18N

        jTextField4.setName("jTextField4"); // NOI18N

        jTextField5.setName("jTextField5"); // NOI18N

        jTextField6.setName("jTextField6"); // NOI18N

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        jLabel6.setText("Price In Term");
        jLabel6.setName("jLabel6"); // NOI18N

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        jLabel5.setText("Price In Cash");
        jLabel5.setName("jLabel5"); // NOI18N

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.setName("jComboBox1"); // NOI18N

        Clear.setText("Clear");
        Clear.setName("Clear"); // NOI18N

        Save.setText("Save");
        Save.setName("Save"); // NOI18N

        Close.setText("Close");
        Close.setActionCommand("Close\n"); // NOI18N
        Close.setName("Close"); // NOI18N
        Close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseActionPerformed(evt);
            }
        });

        jLabel13.setIcon(new javax.swing.ImageIcon("/Users/warz07/Downloads/line2.png")); // NOI18N
        jLabel13.setName("jLabel13"); // NOI18N

        jLabel15.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(204, 0, 0));
        jLabel15.setText("Product Information");
        jLabel15.setName("jLabel15"); // NOI18N

        jLabel16.setText("*Product Unity");
        jLabel16.setName("jLabel16"); // NOI18N

        jLabel17.setText("*Product Description");
        jLabel17.setName("jLabel17"); // NOI18N

        productDescription.setName("productDescription"); // NOI18N

        jLabel18.setText("Purchase Price");
        jLabel18.setName("jLabel18"); // NOI18N

        purchasePrice.setName("purchasePrice"); // NOI18N

        jLabel19.setText("Average Price");
        jLabel19.setName("jLabel19"); // NOI18N

        averagePrice.setName("averagePrice"); // NOI18N

        buyingPrice.setText("Cost Price");
        buyingPrice.setName("buyingPrice"); // NOI18N

        jTextField1.setName("jTextField1"); // NOI18N

        jLabel20.setText("S.T. R($)");
        jLabel20.setName("jLabel20"); // NOI18N

        jTextField2.setText("jTextField2");
        jTextField2.setName("jTextField2"); // NOI18N

        Strprice.setText("0.00");
        Strprice.setName("Strprice"); // NOI18N

        jLabel21.setText("IPI (%)");
        jLabel21.setName("jLabel21"); // NOI18N

        ipiPrice.setText("0.00");
        ipiPrice.setName("ipiPrice"); // NOI18N

        salesLabel.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        salesLabel.setForeground(new java.awt.Color(204, 0, 0));
        salesLabel.setText("Sales Information");
        salesLabel.setName("salesLabel"); // NOI18N

        jLabel7.setText("Final Price");
        jLabel7.setName("jLabel7"); // NOI18N

        jLabel30.setText("Note * items are required");
        jLabel30.setName("jLabel30"); // NOI18N

        jLabel31.setText("Reference 1");
        jLabel31.setName("jLabel31"); // NOI18N

        refreferenceOneProduct.setName("refreferenceOneProduct"); // NOI18N

        jLabel32.setText("Reference 2");
        jLabel32.setName("jLabel32"); // NOI18N

        referenceTwoProduct.setName("referenceTwoProduct"); // NOI18N

        jLabel33.setText("Location");
        jLabel33.setName("jLabel33"); // NOI18N

        locationProduct.setName("locationProduct"); // NOI18N

        jLabel34.setText("Group");
        jLabel34.setName("jLabel34"); // NOI18N

        groupProduct.setName("groupProduct"); // NOI18N

        jLabel35.setText("SubGroup");
        jLabel35.setName("jLabel35"); // NOI18N

        subgroupProduct.setName("subgroupProduct"); // NOI18N

        weightedLabel.setText("Weighted");
        weightedLabel.setName("weightedLabel"); // NOI18N

        yesWeighted.setText("YES");
        yesWeighted.setName("yesWeighted"); // NOI18N

        noWeighted.setText("NO");
        noWeighted.setName("noWeighted"); // NOI18N

        jLabel37.setText("Weight");
        jLabel37.setName("jLabel37"); // NOI18N

        weightProduct.setName("weightProduct"); // NOI18N

        jLabel38.setText("Stock");
        jLabel38.setName("jLabel38"); // NOI18N

        stockProduct.setName("stockProduct"); // NOI18N

        jLabel39.setText("Init. Estimation");
        jLabel39.setName("jLabel39"); // NOI18N

        initialEstimationProduct.setName("initialEstimationProduct"); // NOI18N

        jLabel40.setText("Minimal Estimation");
        jLabel40.setName("jLabel40"); // NOI18N

        minimalEstimation.setName("minimalEstimation"); // NOI18N

        jLabel41.setText("Profit Margin(%)");
        jLabel41.setName("jLabel41"); // NOI18N

        profitMargin.setName("profitMargin"); // NOI18N

        jLabel42.setText("Validity");
        jLabel42.setName("jLabel42"); // NOI18N

        validityProduct.setName("validityProduct"); // NOI18N

        jLabel43.setText("Name in the Printer (24 characters)");
        jLabel43.setName("jLabel43"); // NOI18N

        nameInthePrinter.setName("nameInthePrinter"); // NOI18N

        jLabel44.setText("Commission");
        jLabel44.setName("jLabel44"); // NOI18N

        jRadioButton1.setText("Value");
        jRadioButton1.setName("jRadioButton1"); // NOI18N

        percentageRadioButton.setText("Percentage");
        percentageRadioButton.setName("percentageRadioButton"); // NOI18N

        noneRadioButton.setText("None");
        noneRadioButton.setName("noneRadioButton"); // NOI18N

        jLabel45.setText("Unity Quanitity");
        jLabel45.setName("jLabel45"); // NOI18N

        unityQuantity.setName("unityQuantity"); // NOI18N

        jLabel46.setText("Size");
        jLabel46.setName("jLabel46"); // NOI18N

        sizeProduct.setName("sizeProduct"); // NOI18N

        jLabel47.setText("Taxes");
        jLabel47.setName("jLabel47"); // NOI18N

        taxesProduct.setName("taxesProduct"); // NOI18N

        jLabel48.setText("Commercial Name");
        jLabel48.setName("jLabel48"); // NOI18N

        commercialName.setName("commercialName"); // NOI18N

        jLabel49.setText("Average Cost");
        jLabel49.setName("jLabel49"); // NOI18N

        averageCost.setName("averageCost"); // NOI18N

        jLabel50.setText("Average Final Price");
        jLabel50.setName("jLabel50"); // NOI18N

        averageFinalPrice.setName("averageFinalPrice"); // NOI18N

        jLabel51.setText("Promotional Price");
        jLabel51.setName("jLabel51"); // NOI18N

        promotionalPrice.setName("promotionalPrice"); // NOI18N

        jLabel52.setText("Date product price changed");
        jLabel52.setName("jLabel52"); // NOI18N

        dateProductPriceChange.setText("01/20/2011");
        dateProductPriceChange.setName("dateProductPriceChange"); // NOI18N

        jLabel53.setText("In Cash");
        jLabel53.setName("jLabel53"); // NOI18N

        inCashProduct.setName("inCashProduct"); // NOI18N

        jLabel54.setText("%");
        jLabel54.setName("jLabel54"); // NOI18N

        inCashActual.setName("inCashActual"); // NOI18N

        jLabel55.setText("In Term");
        jLabel55.setName("jLabel55"); // NOI18N

        inTermProduct.setName("inTermProduct"); // NOI18N

        jLabel56.setText("%");
        jLabel56.setName("jLabel56"); // NOI18N

        inTermActual.setName("inTermActual"); // NOI18N

        jLabel57.setText("Promotion");
        jLabel57.setName("jLabel57"); // NOI18N

        jLabel58.setForeground(new java.awt.Color(204, 0, 0));
        jLabel58.setText("Price");
        jLabel58.setName("jLabel58"); // NOI18N

        promotionPrice.setName("promotionPrice"); // NOI18N

        jLabel59.setForeground(new java.awt.Color(204, 0, 0));
        jLabel59.setText("Commision(%)");
        jLabel59.setName("jLabel59"); // NOI18N

        commissionPromotion.setName("commissionPromotion"); // NOI18N

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jTextField2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 0, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(inCashProduct, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 60, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(2, 2, 2)
                .add(jLabel54)
                .add(2, 2, 2)
                .add(inCashActual, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 96, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(683, Short.MAX_VALUE))
            .add(jPanel1Layout.createSequentialGroup()
                .add(20, 20, 20)
                .add(ProductHeader)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 817, Short.MAX_VALUE)
                .add(jLabel30)
                .add(41, 41, 41))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel13, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                    .add(jTextField4)
                                    .add(jLabel5))
                                .add(18, 18, 18)
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jLabel6)
                                    .add(jTextField5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 66, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jLabel34)
                                    .add(groupProduct, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 55, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jPanel1Layout.createSequentialGroup()
                                        .add(jLabel35)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                        .add(jLabel4))
                                    .add(jPanel1Layout.createSequentialGroup()
                                        .add(subgroupProduct, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 53, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .add(18, 18, 18)
                                        .add(productQuantity, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE))))
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                    .add(jPanel1Layout.createSequentialGroup()
                                        .add(jLabel17)
                                        .add(176, 176, 176))
                                    .add(jPanel1Layout.createSequentialGroup()
                                        .add(productDescription, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 297, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)))
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jComboBox1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(jLabel16))))
                        .add(18, 18, 18)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jLabel40)
                                    .add(minimalEstimation, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 95, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jPanel1Layout.createSequentialGroup()
                                        .add(6, 6, 6)
                                        .add(jLabel41))
                                    .add(profitMargin, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 84, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .add(18, 18, 18)
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jLabel42)
                                    .add(validityProduct, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 117, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                            .add(weightedLabel)
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(yesWeighted)
                                    .add(noWeighted))
                                .add(22, 22, 22)
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                    .add(jPanel1Layout.createSequentialGroup()
                                        .add(weightProduct, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 67, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(stockProduct, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 65, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                        .add(initialEstimationProduct))
                                    .add(jPanel1Layout.createSequentialGroup()
                                        .add(14, 14, 14)
                                        .add(jLabel37)
                                        .add(31, 31, 31)
                                        .add(jLabel38)
                                        .add(30, 30, 30)
                                        .add(jLabel39))))))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(productName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 180, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(4, 4, 4)
                                .add(jLabel2)))
                        .add(18, 18, 18)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel3)
                            .add(ProductId, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 124, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(35, 35, 35)
                                .add(jLabel31))
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(18, 18, 18)
                                .add(refreferenceOneProduct, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 107, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(30, 30, 30)
                                .add(jLabel32))
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(18, 18, 18)
                                .add(referenceTwoProduct, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 159, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                        .add(35, 35, 35)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel33)
                            .add(locationProduct, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 131, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(314, Short.MAX_VALUE))
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel44)
                .addContainerGap(1115, Short.MAX_VALUE))
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jRadioButton1)
                .addContainerGap(1131, Short.MAX_VALUE))
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(percentageRadioButton)
                .addContainerGap(1097, Short.MAX_VALUE))
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(noneRadioButton)
                .addContainerGap(1132, Short.MAX_VALUE))
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(nameInthePrinter, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 286, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel43))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jLabel45)
                        .add(18, 18, 18)
                        .add(jLabel46))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(unityQuantity, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 85, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(sizeProduct, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 60, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .add(1, 1, 1)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(taxesProduct, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 123, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel47))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel48)
                    .add(commercialName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 215, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(394, Short.MAX_VALUE))
            .add(jPanel1Layout.createSequentialGroup()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jLabel1, 0, 0, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel1Layout.createSequentialGroup()
                        .add(29, 29, 29)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(Strprice, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 45, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(jLabel21))
                                .add(18, 18, 18)
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                    .add(jLabel20, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .add(ipiPrice, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 56, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .add(18, 18, 18)
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                    .add(dateProductPriceChange)
                                    .add(jLabel52, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .add(jLabel15)
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(salesLabel)
                                    .add(jPanel1Layout.createSequentialGroup()
                                        .add(jLabel53)
                                        .add(123, 123, 123)
                                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                            .add(jPanel1Layout.createSequentialGroup()
                                                .add(inTermProduct, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 57, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                                .add(2, 2, 2)
                                                .add(jLabel56)
                                                .add(2, 2, 2)
                                                .add(inTermActual, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 92, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                            .add(jLabel55))))
                                .add(2, 2, 2)
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                    .add(jLabel57, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .add(jLabel58)
                                    .add(promotionPrice))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                    .add(commissionPromotion)
                                    .add(jLabel59, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                    .add(purchasePrice, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                                    .add(jLabel18))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jLabel19)
                                    .add(averagePrice, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 96, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                    .add(buyingPrice)
                                    .add(jTextField1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 71, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                    .add(averageCost)
                                    .add(jLabel49, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jLabel7)
                                    .add(jTextField6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 79, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .add(18, 18, 18)
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                    .add(averageFinalPrice)
                                    .add(jLabel50))
                                .add(10, 10, 10)
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(promotionalPrice, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 138, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(jLabel51)
                                    .add(jPanel1Layout.createSequentialGroup()
                                        .add(Save, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 82, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                        .add(Clear, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 85, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                        .add(Close, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 79, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(ProductHeader)
                    .add(jLabel30))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel13)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(10, 10, 10)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel3)
                            .add(jLabel31))
                        .add(3, 3, 3)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(ProductId, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(refreferenceOneProduct, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jLabel2)
                        .add(3, 3, 3)
                        .add(productName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(locationProduct, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                    .add(jLabel32)
                                    .add(jLabel33))
                                .add(3, 3, 3)
                                .add(referenceTwoProduct, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(jPanel1Layout.createSequentialGroup()
                            .add(jLabel6)
                            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                            .add(jTextField5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 28, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(jPanel1Layout.createSequentialGroup()
                            .add(jLabel5)
                            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                            .add(jTextField4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                    .add(jLabel35)
                                    .add(jLabel4))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                    .add(subgroupProduct, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(productQuantity, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 29, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(jLabel34)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(groupProduct, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                    .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(jPanel1Layout.createSequentialGroup()
                            .add(4, 4, 4)
                            .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                .add(jLabel37)
                                .add(jLabel38)
                                .add(jLabel39))
                            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                            .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                .add(weightProduct, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(stockProduct, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(initialEstimationProduct, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                        .add(jPanel1Layout.createSequentialGroup()
                            .add(weightedLabel)
                            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                            .add(yesWeighted)
                            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                            .add(noWeighted))))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jLabel17)
                        .add(36, 36, 36))
                    .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(jPanel1Layout.createSequentialGroup()
                            .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                .add(jLabel16)
                                .add(jLabel40))
                            .add(3, 3, 3)
                            .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                .add(jComboBox1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(productDescription, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(minimalEstimation, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                        .add(jPanel1Layout.createSequentialGroup()
                            .add(jLabel41)
                            .add(3, 3, 3)
                            .add(profitMargin, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(jPanel1Layout.createSequentialGroup()
                            .add(jLabel42)
                            .add(3, 3, 3)
                            .add(validityProduct, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel43)
                    .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(jLabel45)
                        .add(jLabel46)
                        .add(jLabel47))
                    .add(jLabel48))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(nameInthePrinter, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(unityQuantity, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 28, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(sizeProduct, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(taxesProduct, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(commercialName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(5, 5, 5)
                .add(jLabel44)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jRadioButton1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(percentageRadioButton)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(noneRadioButton)
                .add(13, 13, 13)
                .add(jLabel1)
                .add(4, 4, 4)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jLabel15)
                        .add(18, 18, 18)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel18)
                            .add(jLabel19)
                            .add(buyingPrice)
                            .add(jLabel49)
                            .add(jLabel7))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(purchasePrice, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(averagePrice, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jTextField1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(averageCost, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jTextField6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel50)
                            .add(jLabel51))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(averageFinalPrice, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(promotionalPrice, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jLabel20)
                                    .add(jLabel21))
                                .add(8, 8, 8)
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                    .add(Strprice, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(ipiPrice, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(dateProductPriceChange, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(16, 16, 16)
                                .add(jLabel52)))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(salesLabel)
                        .add(7, 7, 7)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel53)
                            .add(jLabel55))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(77, 77, 77)
                        .add(jLabel57)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel58)
                            .add(jLabel59))
                        .add(4, 4, 4)))
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jTextField2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(inCashProduct, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel54)
                    .add(inCashActual, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(inTermProduct, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel56)
                    .add(inTermActual, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(promotionPrice, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(commissionPromotion, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(Save, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 29, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(Clear, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 29, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(Close, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 29, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        SearchTab.addTab("New Product", jPanel1);

        jPanel2.setName("jPanel2"); // NOI18N

        updateProductButton.setText("Update");
        updateProductButton.setName("updateProductButton"); // NOI18N

        deleteProductButton.setText("Delete");
        deleteProductButton.setName("deleteProductButton"); // NOI18N

        cancelProductButton.setText("Cancel");
        cancelProductButton.setActionCommand("");
        cancelProductButton.setName("cancelProductButton"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        updateTableProduct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        updateTableProduct.setName("updateTableProduct"); // NOI18N
        jScrollPane1.setViewportView(updateTableProduct);

        searchUpdateButtonProduct.setText("Search");
        searchUpdateButtonProduct.setName("searchUpdateButtonProduct"); // NOI18N

        jLabel23.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel23.setText("Update/Delete Product ");
        jLabel23.setName("jLabel23"); // NOI18N

        jLabel24.setIcon(new javax.swing.ImageIcon("/Users/warz07/Downloads/line2.png")); // NOI18N
        jLabel24.setName("jLabel24"); // NOI18N

        jLabel25.setText("Product Code");
        jLabel25.setName("jLabel25"); // NOI18N

        productCodeUpdate.setName("productCodeUpdate"); // NOI18N

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(927, Short.MAX_VALUE)
                .add(updateProductButton)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(deleteProductButton)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(cancelProductButton)
                .addContainerGap())
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel2Layout.createSequentialGroup()
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jLabel24, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 1182, Short.MAX_VALUE)
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(20, 20, 20)
                        .add(jLabel23)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 614, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .add(32, 32, 32))
            .add(jPanel2Layout.createSequentialGroup()
                .add(766, 766, 766)
                .add(searchUpdateButtonProduct)
                .addContainerGap())
            .add(jPanel2Layout.createSequentialGroup()
                .add(9, 9, 9)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 842, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel25)
                    .add(productCodeUpdate, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 131, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(363, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel23)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel24)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel25)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(productCodeUpdate, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 115, Short.MAX_VALUE)
                .add(searchUpdateButtonProduct)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 431, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(9, 9, 9)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(updateProductButton)
                    .add(deleteProductButton)
                    .add(cancelProductButton))
                .addContainerGap())
        );

        SearchTab.addTab("Update/Delete", jPanel2);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(104, 104, 104)
                .add(SearchTab, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 903, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(94, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(SearchTab, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ProductIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProductIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProductIdActionPerformed

    private void CloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseActionPerformed
        
                //product_view.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

    }//GEN-LAST:event_CloseActionPerformed

    /**
     * @param args the command line arguments
     *
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Product_View().setVisible(true);
            }
        });
    }
    */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Clear;
    private javax.swing.JButton Close;
    private javax.swing.JLabel ProductHeader;
    private javax.swing.JTextField ProductId;
    private javax.swing.JButton Save;
    private javax.swing.JButton Search;
    private javax.swing.JButton SearchButton;
    private javax.swing.JTabbedPane SearchTab;
    private javax.swing.JTextField Strprice;
    private javax.swing.JButton advanceSearch;
    private javax.swing.JTextField averageCost;
    private javax.swing.JTextField averageFinalPrice;
    private javax.swing.JTextField averagePrice;
    private javax.swing.JLabel buyingPrice;
    private javax.swing.JButton cancelProductButton;
    private javax.swing.JTextField commercialName;
    private javax.swing.JTextField commissionPromotion;
    private javax.swing.JTextField currentStockSearch;
    private javax.swing.JTextField dateProductPriceChange;
    private javax.swing.JButton deleteProductButton;
    private javax.swing.JTextField descriptionSearch;
    private javax.swing.JTextField finalPriceSearch;
    private javax.swing.JTextField groupProduct;
    private javax.swing.JTextField inCashActual;
    private javax.swing.JTextField inCashProduct;
    private javax.swing.JTextField inTermActual;
    private javax.swing.JTextField inTermProduct;
    private javax.swing.JTextField initialEstimationProduct;
    private javax.swing.JTextField ipiPrice;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField locationProduct;
    private javax.swing.JTextField minimalEstimation;
    private javax.swing.JTextField nameInthePrinter;
    private javax.swing.JRadioButton noWeighted;
    private javax.swing.JRadioButton noneRadioButton;
    private javax.swing.JRadioButton percentageRadioButton;
    private javax.swing.JTextField priceInTermSearch;
    private javax.swing.JTextField priceinCashSearch;
    private javax.swing.JTextField productCodeUpdate;
    private javax.swing.JTextField productCostSearch;
    private javax.swing.JTextField productDescription;
    private javax.swing.JLabel productIDLabel;
    private javax.swing.JTextField productName;
    private javax.swing.JTextField productNameSearch;
    private javax.swing.JLabel productNameSearchLabel;
    private javax.swing.JTextField productQuantity;
    private javax.swing.JTextField productSearch;
    private javax.swing.JPanel productSearchTable;
    private javax.swing.JTextField profitMargin;
    private javax.swing.JTextField promotionPrice;
    private javax.swing.JTextField promotionalPrice;
    private javax.swing.JTextField purchasePrice;
    private javax.swing.JLabel referenceLabel;
    private javax.swing.JTextField referenceProduct;
    private javax.swing.JTextField referenceTwoProduct;
    private javax.swing.JTextField refreferenceOneProduct;
    private javax.swing.JLabel salesLabel;
    private javax.swing.JButton searchUpdateButtonProduct;
    private javax.swing.JTextField sizeProduct;
    private javax.swing.JCheckBox sortPriceProduct;
    private javax.swing.JCheckBox sortProductDate;
    private javax.swing.JCheckBox sortProductName;
    private javax.swing.JTextField stockProduct;
    private javax.swing.JTextField subgroupProduct;
    private javax.swing.JTextField taxesProduct;
    private javax.swing.JTextField trademarkProduct;
    private javax.swing.JTextField unityQuantity;
    private javax.swing.JComboBox unitySearch;
    private javax.swing.JButton updateProductButton;
    private javax.swing.JTable updateTableProduct;
    private javax.swing.JTextField validityProduct;
    private javax.swing.JTextField weightProduct;
    private javax.swing.JLabel weightedLabel;
    private javax.swing.JRadioButton yesWeighted;
    // End of variables declaration//GEN-END:variables



}
